# Project information
site_name: SceneryStack
site_url: https://scenerystack.org/
site_author: PhET Interactive Simulations
site_description: >-
  This site houses resources for the developer community using SceneryStack
  to create inclusive, multimodal web interactives in HTML5.

# Repository
repo_name: community
repo_url: https://github.com/scenerystack/community
edit_uri: edit/main/docs

# Configuration
theme:
  name: material
  # custom_dir: docs/overrides
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - content.tooltips
    - header.autohide
    # - navigation.expand
    # - navigation.footer
    - navigation.indexes
    - navigation.instant
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  favicon: assets/scenerystack-round.png
  logo: assets/scenerystack-round.png
  name: material
  palette:
    # Palette toggle for automatic mode
  - media: "(prefers-color-scheme)"
    toggle:
      icon: material/brightness-auto
      name: Switch to light mode
  - media: '(prefers-color-scheme: light)'
    primary: grey
    accent: light blue
    scheme: default
    toggle:
      icon: material/weather-sunny
      name: Switch to dark mode
  - media: '(prefers-color-scheme: dark)'
    primary: blue
    accent: deep orange
    scheme: slate
    toggle:
      icon: material/weather-night
      name: Switch to system preference
  font:
    text: Roboto Condensed
    code: Roboto Mono

# Plugins
plugins:
  - blog
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true

# Customization
extra:
  annotate:
    json: [.s2]
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/phetsims/paper-land

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

nav:
    - Overview: index.md
    - Getting Started:
      - guides/pathways.md
      - Web Development:
        - Scenery and phet-lib: guides/scenery.md
        - (pending) Walkthrough: guides/walkthrough.md
      - Simulation Development:
        - guides/simulation/simulation-development.md
        - PhET Development Guide: info-sync/simulation-development-overview.md
        - Intro Sim Exercises: info-sync/scenerystack-exercises.md
        - Software Design Patterns: info-sync/phet-software-design-patterns.md
        - PhET Sim Tooling: info-sync/chipper-deploy.md
        - PhET TypeScript Conventions: info-sync/typescript-conventions.md
      - Examples:
        - guides/scenery-examples.md
        - guides/simulation-examples.md
      - Maintenance: guides/breaking.md
    - Reference: 
      - Libraries: guides/scenerystack_list.md
      - Scenery: https://phetsims.github.io/scenery/
      - Dot: https://phetsims.github.io/dot/
      - Kite: https://phetsims.github.io/kite/
      - Alpenglow: https://phetsims.github.io/alpenglow/
    - Accessibility Resources:
      - accessibility/phet_a11y_guides.md
    - Community:
      - Join Us: join.md 
      - Community Guidelines: CODE_OF_CONDUCT.md
      - Sustainability Plan: sustainability_plan.md
      - Contribute:
        - Contribution Guide: CONTRIBUTING.md
        - Contributor License Agreement: CLA.md
        - Coding Conventions: info-sync/coding-conventions.md
        - Roadmap: roadmap.md
    - FAQ: guides/faqs.md





