# Project information
site_name: SceneryStack
site_url: https://scenerystack.org/
site_author: PhET Interactive Simulations
site_description: >-
  The TypeScript webstack for creating inclusive, multimodal web interactives.

# Repository
repo_name: community
repo_url: https://github.com/scenerystack/community
edit_uri: edit/main/docs

extra:
  version:
    provider: mike # for versioning plugin

extra_css:
  - stylesheets/extra.css

# extra_javascript:
#   - javascripts/extra.js

# Configuration
theme:
  name: material
  custom_dir: overrides
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - content.tooltips
    - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    # - navigation.prune
    # - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  favicon: assets/scenerystack-round.png
  logo: assets/scenerystack-round.png
  name: material
  palette:
    # Palette toggle for automatic mode
  - media: "(prefers-color-scheme)"
    toggle:
      icon: material/brightness-auto
      name: Switch to light mode
  - media: '(prefers-color-scheme: light)'
    primary: blue
    accent: orange
    scheme: default
    toggle:
      icon: material/weather-sunny
      name: Switch to dark mode
  - media: '(prefers-color-scheme: dark)'
    primary: blue
    accent: light blue
    scheme: slate
    toggle:
      icon: material/weather-night
      name: Switch to system preference
  font:
    text: Noto Sans
    code: Noto Sans Mono

# Plugins
plugins:
  # - blog
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true

# Customization
extra:
  annotate:
    json: [.s2]
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/scenerystack/
    - icon: fontawesome/brands/mastodon
      link: https://mastodon.social/@scenerystack
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@SceneryStack
    

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

nav:
  - Introduction: index.md
  - Learn:
    - Overview: learn/overview.md
    - Getting Started:
      - Prerequisites: learn/prerequisites.md
      - Simulation: learn/simulation.md
      - Scenery Application: learn/scenery-application.md
      - Standalone Library: learn/standalone-library.md
    - Guides:
      - Scenery Basics: learn/scenery-basics.md
      - Scenery Layout: learn/scenery-layout.md
      - Scenery Input: learn/scenery-input.md
      - Scenery Accessibility: learn/scenery-accessibility.md
      - Emitters and Properties: learn/emitters-and-properties.md
      - Vectors and Matrices: learn/vectors-and-matrices.md
      - Shapes: learn/shapes.md
      - Best Practices: learn/best-practices.md
    - Tutorials:
      - Three.js Integration: learn/threejs-integration.md
      - Simulation Exercises: learn/simulation-exercises.md
    - Examples:
      - Demo Simulation: learn/examples/demo-simulation.md
      - Scenery Layout: learn/examples/scenery-layout.md
      - Simulation Showcase: learn/examples/simulation-showcase.md
      - Application Showcase: learn/examples/application-showcase.md
    - Overview:
      - Install: learn/setup.md
      - Create a New Project: learn/templates/projecta_rasa.md
      - Make a Simulation: learn/templates/simula_rasa.md
      - Add SceneryStack to a Project: learn/templates/subprojecta_rasa.md
    - Guides: 
      - Web Overview: learn/web/web_overview.md
      - Full Project Demo: learn/web/scenery_demo.md
      - Coding Conventions: info_sync/coding_conventions.md
      - PhET TypeScript Conventions: info_sync/typescript_conventions.md
    - Examples:
      - Exercises: info_sync/scenerystack_exercises.md
  - Reference:
    - Libraries: reference/scenerystack_list.md
    - Software Design Patterns: info_sync/software_design_patterns.md
    - Library APIs:
      - Scenery: https://phetsims.github.io/scenery/
      - Dot: https://phetsims.github.io/dot/
      - Kite: https://phetsims.github.io/kite/
      - Alpenglow: https://phetsims.github.io/alpenglow/
    - Accessibility Resources: accessibility/a11y_guides.md
  - Community:
    - Join Us: community/join.md 
    - Community Guidelines: CODE_OF_CONDUCT.md
    - Sustainability Plan: community/sustainability_plan.md
    - Contribute:
      - Contribution Guide: CONTRIBUTING.md
      - Contributor License Agreement: community/CLA.md
      - Setting Up Development Environment: learn/dev/dev_environment.md
      - SceneryStack Versioning: learn/dev/versioning.md
      - Roadmap: community/roadmap.md
  - About: 
    - Project Mission: about/about.md
    - FAQ: about/faqs.md
    - Branding: about/branding.md
    - Licensing: about/licensing.md





