# Project information
site_name: SceneryStack
site_url: https://scenerystack.github.io/community/
site_author: PhET Interactive Simulations
site_description: >-
  This site houses resources for the developer community using the libraries within SceneryStack 
  to create interactive simulations and other web interactives in HTML5.

# Repository
repo_name: community
repo_url: https://github.com/scenerystack/community
edit_uri: edit/main/docs

# Configuration
theme:
  name: material
  # custom_dir: docs/overrides
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.tabs.link
    - content.tooltips
    - header.autohide
    # - navigation.expand
    # - navigation.footer
    - navigation.indexes
    - navigation.instant
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  favicon: assets/scenerystack-round.png
  logo: assets/scenerystack-round.png
  name: material
  palette:
  - media: '(prefers-color-scheme: light)'
    primary: blue
    accent: yellow
    scheme: default
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode
  - media: '(prefers-color-scheme: dark)'
    primary: blue
    accent: yellow
    scheme: slate
    toggle:
      icon: material/brightness-4
      name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono

# Plugins
plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true

# Customization
extra:
  annotate:
    json: [.s2]
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/phetsims/paper-land

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

nav:
    - Home: index.md
    - Guides:
      - guides/pathways.md
      - SceneryStack for the Web:
        - Scenery and phet-lib: guides/scenery.md
        - Stack List: guides/scenerystack_list.md
      - SceneryStack for Simulations:
        - guides/simulation/simulation-development.md
        - PhET Development Overview: info-sync/simulation-development-overview.md
        - Simulation Exercises: info-sync/scenerystack-exercises.md
        - Coding Conventions: info-sync/coding-conventions.md
        - PhET Sim Tooling: info-sync/chipper-deploy.md
        - PhET TypeScript Conventions: info-sync/typescript-conventions.md
      - Examples:
        - Examples: guides/scenery-examples.md
        - Simulation Examples: guides/simulation-examples.md
    - Community:
      - Join Us!: community.md 
      - Community Guidelines: CODE_OF_CONDUCT.md
      - Sustainability Plan: sustainability_plan.md
      - Contribute:
        - CONTRIBUTING.md
        - Contributor License Agreement: CLA.md
        - Software Design Patterns: info-sync/phet-software-design-patterns.md
        - Roadmap: roadmap.md
    - Accessibility Resources:
      - Accessibility in Scenery: accessibility/scenery_a11y.md
      - PhET Accessibility Guides: accessibility/phet_a11y_guides.md





