# Project information
site_name: SceneryStack
site_url: https://scenerystack.org/
site_author: PhET Interactive Simulations
site_description: >-
  The TypeScript webstack for creatng inclusive, multimodal web interactives.

# Repository
repo_name: community
repo_url: https://github.com/scenerystack/community
edit_uri: edit/main/docs

extra:
  version:
    provider: mike # for versioning plugin

extra_css:
  - stylesheets/extra.css

# extra_javascript:
#   - javascripts/extra.js

# Configuration
theme:
  name: material
  custom_dir: overrides
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - content.tooltips
    - header.autohide
    # - navigation.expand
    # - navigation.footer
    - navigation.indexes
    - navigation.instant
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  favicon: assets/scenerystack-round.png
  logo: assets/scenerystack-round.png
  name: material
  palette:
    # Palette toggle for automatic mode
  - media: "(prefers-color-scheme)"
    toggle:
      icon: material/brightness-auto
      name: Switch to light mode
  - media: '(prefers-color-scheme: light)'
    primary: indigo
    accent: light blue
    scheme: default
    toggle:
      icon: material/weather-sunny
      name: Switch to dark mode
  - media: '(prefers-color-scheme: dark)'
    primary: indigo
    accent: light blue
    scheme: slate
    toggle:
      icon: material/weather-night
      name: Switch to system preference
  font:
    text: Roboto Condensed
    code: Roboto Mono

# Plugins
plugins:
  - blog
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true

# Customization
extra:
  annotate:
    json: [.s2]
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/phetsims/paper-land

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

nav:
    - Overview: index.md
    - Getting Started: 
      - Choose Your Path: guides/pathways.md
      - Setup: guides/setup.md
      - Web Integration: 
        - Walkthrough: guides/scenery.md
      - Framework: 
        - Walkthrough: guides/framework/framework.md
        - Building: guides/framework/build.md
        - Exercises: info_sync/scenerystack_exercises.md
      - SceneryStack Development:
        - Setting Up Development Environment: info_sync/simulation_development_overview.md
        - SceneryStack Versioning: guides/versioning.md
      - Examples:
        - SceneryStack Examples: guides/scenery_examples.md
        - Simulation Examples: guides/simulation_examples.md
      - Maintenance: guides/breaking.md
    - Reference: 
      - Libraries: guides/scenerystack_list.md
      - Software Design Patterns: info_sync/software_design_patterns.md
      - Library APIs:
        - Scenery: https://phetsims.github.io/scenery/
        - Dot: https://phetsims.github.io/dot/
        - Kite: https://phetsims.github.io/kite/
        - Alpenglow: https://phetsims.github.io/alpenglow/
      - Resources from PhET:
        - PhET Sim Tooling: info_sync/chipper_deploy.md
        - PhET TypeScript Conventions: info_sync/typescript_conventions.md
    - Accessibility Resources:
      - accessibility/phet_a11y_guides.md
    - Community:
      - Join Us: join.md 
      - Community Guidelines: CODE_OF_CONDUCT.md
      - Sustainability Plan: sustainability_plan.md
      - Contribute:
        - Contribution Guide: CONTRIBUTING.md
        - Contributor License Agreement: CLA.md
        - Coding Conventions: info_sync/coding_conventions.md
        - Roadmap: roadmap.md
    - FAQ: guides/faqs.md





